
//PROMISE => ASENKRON BIR ISLEMIN BASARIYLA BITIP BITMEDIGINI GOSTEREN BIR OBJECT YAPISIDIR.
//
//PENDING => ILK STATE, BASARILI VEYA BASARISIZ OLMAYAN
//FULFILLED => ISLEMIN BASARIYLA TAMAMLANMASI
//REJECTED => ISLEMIN BASARIYLA TAMAMLANMAMASI

//1-) PROMISE YAPISI OBJECT OLDUGU ICIN "new Promise()" CONSTRUCTOR'I ILE YENI BIR PROMISE NESNESI OLUSTURULUR.
//2-) CONSTRUCTOR'A ASIL ISLEMLERI YAPMASI ICIN "executor" FONKSIYONU VERILIR. BU FONKSIYONUN 2 PARAMETRESI VARDIR : "resolve , reject" FONKSIYONLARI
//3-) BASARILI TAMAMLANIRSA RESOLVE FONK. CALISIR.
//4-) BASARISIZ TAMAMLANIRSA REJECT FONK. CALISIR.